name: base
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - archspec=0.2.1=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py310h06a4308_0
  - beautifulsoup4=4.12.2=py310h06a4308_0
  - blas=1.0=mkl
  - boltons=23.0.0=py310h06a4308_0
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - chardet=4.0.0=py310h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310h06a4308_0
  - cmake=3.26.4=h96355d8_0
  - conda=23.9.0=py310h06a4308_0
  - conda-build=24.1.2=py310h06a4308_0
  - conda-content-trust=0.2.0=py310h06a4308_0
  - conda-index=0.4.0=pyhd3eb1b0_0
  - conda-libmamba-solver=23.7.0=py310h06a4308_0
  - conda-package-handling=2.2.0=py310h06a4308_0
  - conda-package-streaming=0.9.0=py310h06a4308_0
  - cryptography=42.0.2=py310hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - decorator=5.1.1=pyhd3eb1b0_0
  - distro=1.8.0=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - fmt=9.1.0=hdb19cb5_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.20.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.3=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.19.2=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libarchive=3.6.2=h6ac8c49_2
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcurl=8.4.0=h251f7ec_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblief=0.12.3=h6a678d5_0
  - libmamba=1.5.3=haf1ee3a_0
  - libmambapy=1.5.3=py310h2dafd23_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsolv=0.7.24=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxml2=2.10.4=hf1b16e4_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - menuinst=2.0.2=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - more-itertools=10.1.0=py310h06a4308_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.26.3=py310h5f9d8c6_0
  - numpy-base=1.26.3=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.1=py310h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.17.2=h6a678d5_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.2.0=py310h5eee18b_0
  - pip=23.3.1=py310h06a4308_0
  - pkginfo=1.9.6=py310h06a4308_0
  - platformdirs=3.10.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-lief=0.12.3=py310h6a678d5_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pyopenssl=24.0.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py310h06a4308_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.31.0=py310h06a4308_1
  - rhash=1.4.3=hdbd6064_0
  - rpds-py=0.10.6=py310hb02cf49_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=py310h06a4308_0
  - torchvision=0.17.1=py310_cu121
  - tqdm=4.65.0=py310h2f386ee_0
  - traitlets=5.7.1=py310h06a4308_0
  - truststore=0.8.0=py310h06a4308_0
  - typing_extensions=4.9.0=py310h06a4308_1
  - tzdata=2023c=h04d1e81_0
  - urllib3=2.1.0=py310h06a4308_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - audioread==3.0.1
      - auraloss==0.4.0
      - babel==2.14.0
      - bash-kernel==0.9.3
      - bleach==6.1.0
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - expecttest==0.2.1
      - fastjsonschema==2.19.1
      - fonttools==4.50.0
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - h11==0.14.0
      - h5py==3.10.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - hypothesis==6.98.10
      - iniconfig==2.0.0
      - ipykernel==6.29.3
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - joblib==1.3.2
      - json5==0.9.24
      - jupyter==1.0.0
      - jupyter-archive==3.4.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-http-over-ws==0.0.8
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.42.0
      - matplotlib==3.8.3
      - mistune==3.0.2
      - msgpack==1.0.8
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.3
      - nbzip==0.1.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - neural-audio-spring-reverb==0.5.0
      - neutone-sdk==1.4.2
      - notebook==7.1.2
      - notebook-shim==0.2.4
      - numba==0.59.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - optree==0.10.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pluggy==1.4.0
      - pooch==1.8.1
      - prometheus-client==0.20.0
      - protobuf==4.25.3
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - python-etcd==0.4.5
      - python-json-logger==2.0.7
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - send2trash==1.8.2
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tinycss2==1.2.1
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchelastic==0.2.2
      - torchinfo==1.8.0
      - tornado==6.4
      - triton==2.1.0
      - types-dataclasses==0.6.6
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - wandb==0.16.4
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.10
prefix: /opt/conda
